url: https://close.ac/
# baseurl: 



# Site settings
title: Close
email: support@license.academy
description: "B2B Sales / Top Closers / Services / Skills Coaching"


# Team names, titles and social links


#people:
#name: Raju Basumatary
#pic: 1
#position: Founder
#social:
#title: LinkedIn
#url: 


    #- title: facebook
    #  url: #
    #- title: stack-overflow
    #  url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
 # - title: twitter
 #   url: http://twitter.com/jekyllrb
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket 
 #   url: http://bitbucket.org/jekyll
 #   title: github
 #  url: https://github.com/digifaire

# Postal address (add as many lines as necessary)
# address:
#  - line: 
#  - line: 

# Build settings
markdown: kramdown
permalink: pretty

